// const DISPLAY_COUNT = 10;
const DISPLAY_COUNT = 10;
const OPPONENTS_COUNT = 100;
const DATES_COUNT = 10 + 1;
const TRANSITION_VALUES_COUNT = 50;
const SMOOTHING_FACTOR = 25;

const CHART_UPDATE_DELAY = 3000;
const COLOR_ANIMATION_DURATION = CHART_UPDATE_DELAY / 2;
const Y_SCALE_ANIMATION_DURATION = CHART_UPDATE_DELAY;
const X_SCALE_ANIMATION_DURATION = CHART_UPDATE_DELAY;

const IMAGE_URL =
  "https://img.freepik.com/free-icon/soccer-player_318-174100.jpg";

const IS_TOUCH_DEVICE = "ontouchstart" in window;

// let canApplyTransitionsOfXAxis = false;

// setTimeout(() => (canApplyTransitionsOfXAxis = true), 500);

const RANDOM_NAMES = [
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
  "Silas Wagner",
  "Jarred Walters",
  "Cleo Watts",
  "Josefa Costa",
  "Kasey Robertson",
  "Max Skinner",
  "Edgar Bright",
  "Shannon Roberts",
  "Jerald Carson",
  "Al Kline",
  "Lesley Peters",
  "Dallas Hill",
  "Jewel Flynn",
  "Margo Harrell",
  "Silvia Alvarado",
  "Eve Burch",
  "Christoper Wong",
  "Emma Farrell",
  "Tomas Newman",
  "Raymundo Barnett",
  "Rocco Kim",
  "Jayson Barber",
  "Lessie Lowery",
  "Stacie Stafford",
  "Garth Vasquez",
  "Nickolas Matthews",
  "Rosario Gilmore",
  "Jillian Hicks",
  "Gail Santana",
  "Omar Boyd",
  "Veronica Riddle",
  "Tabitha Weaver",
  "Mattie Spence",
  "Nelson Ballard",
  "Josephine Mccarty",
  "Bert Calderon",
  "Rowena Patterson",
  "Francisca Wilkerson",
  "Marva Baldwin",
  "Myra Espinoza",
  "Heriberto Padilla",
  "Felton Bass",
  "Effie Combs",
  "Leonor Campos",
  "Irma Middleton",
  "Clark Wall",
  "Dorothy Harrison",
  "Palmer Jarvis",
  "Antwan Ball",
  "Ervin Aguirre",
  "Otto Robles",
  "Trent Moreno",
  "Francisco Carney",
  "Delores Abbott",
  "Wayne Turner",
  "Hillary Powell",
  "Vicki Crawford",
  "Vance Avery",
  "Darell Gibson",
  "Shauna Rodriguez",
  "Melissa Thornton",
  "Ronda Bowers",
  "Tobias Lloyd",
  "Jane Villanueva",
  "Joel Parks",
  "Jolene Jackson",
  "Marcellus Berry",
  "Foster Buck",
  "Brandie Hawkins",
  "Darrell Erickson",
  "Millicent Ho",
  "Thaddeus Simmons",
  "Carson Dalton",
  "Christian Flores",
  "Bert Mooney",
  "Micheal House",
  "Lindsey Novak",
  "Murray Pope",
  "Wilbert Rojas",
  "Helen Stein",
  "Josefina Chambers",
  "Kari Decker",
  "Estelle Ewing",
  "Cliff Pugh",
  "Korey Mcfarland",
  "Elsie York",
  "Alice Cooper",
  "Mattie Hobbs",
  "Lilian Zuniga",
  "Amos Duffy",
  "Ronny Munoz",
  "Leo Oconnor",
  "Curt Rowe",
  "Sharron Cruz",
  "Thurman Harrington",
  "Cary Richmond",
  "Jerry Stephenson",
  "Margery Hunt",
  "Rebekah Rivas",
  "Beverley Austin",
]
  .map((name, i) => `${name} ${i}`)
  .slice(0, OPPONENTS_COUNT);

let aspectRatio = IS_TOUCH_DEVICE
  ? 1 / (DISPLAY_COUNT / 10)
  : DISPLAY_COUNT == 10
  ? 2
  : 1 / (DISPLAY_COUNT / 15);

function useSmoothRandom(factor, start) {
  let last = start !== undefined ? start : Math.random();
  const halfEnvelope = 1 / factor / 2;
  return function () {
    // clamp output range to [0,1] as Math.random()
    const max = Math.min(1, last + halfEnvelope);
    const min = Math.max(0.5, last - halfEnvelope);
    // return a number within halfRange of the last returned value
    return (last = Math.random() * (max - min) + min);
  };
}

function getDates() {
  return Array.from({ length: DATES_COUNT }, (_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - i);
    return date;
  }).sort((a, b) => a - b);
}

function getValuesByName() {
  const valuesByName = {};
  for (let i = 0; i < RANDOM_NAMES.length; i++) {
    const name = RANDOM_NAMES[i];
    let smoothRandom = useSmoothRandom(SMOOTHING_FACTOR);
    let values = [];
    while (values.length < DATES_COUNT) {
      values.push({
        value: smoothRandom(),
        name: name,
        date: dates[values.length].toISOString(),
      });
    }
    const parsedValues = values.map((v) => {
      return {
        ...v,
        value: v.value * 100,
        displayValue: (v.value * 100).toFixed(2),
      };
    });
    valuesByName[name] = {
      name: name,
      values: parsedValues,
    };
  }
  return valuesByName;
}

const dates = getDates();

const valuesByName = getValuesByName();

function getDatasets() {
  const datasets = dates.map((date) => {
    const datapoints = Object.values(valuesByName).map((v, i) => {
      const value = v.values.find((v) => v.date === date.toISOString());
      const name = v.name;
      const normalizedName = name.replace(/\s/g, "-").toLowerCase();
      const displayName = name.split(" ").slice(0, 2).join(" ");
      return {
        id: `${normalizedName}-${i}`,
        x: value.value,
        nextDatapoint: null,
        previousDatapoint: null,
        transitionValues: [],
        y: name,
        rank: null,
        value: value.value,
        displayValue: value.displayValue,
        name: name,
        displayName: displayName,
        normalizedName: normalizedName,
        date: date.toISOString(),
      };
    });

    return {
      label: date.toISOString(),
      data: datapoints,
      dataForTransition: [],
      backgroundColor: `transparent`,
      borderColor: `transparent`,
    };
  });

  datasets.forEach((dataset, datasetIndex) => {
    dataset.data
      .sort((a, b) => b.x - a.x)
      .forEach((datapoint, i) => {
        datapoint.rank = i + 1;
      });
    dataset.dataForTransition.push(
      ...dataset.data.filter((d) => d.rank <= DISPLAY_COUNT)
    );
    const { data } = dataset;
    let previousDataset = datasetIndex > 0 ? datasets[datasetIndex - 1] : null;
    let nextDataset =
      datasetIndex < datasets.length - 1 ? datasets[datasetIndex + 1] : null;
    data.forEach((datapoint) => {
      if (previousDataset) {
        const previousDatapoint = previousDataset.data.find(
          (d) => d.normalizedName == datapoint.normalizedName
        );
        const min = Math.min(datapoint.value, previousDatapoint.value);
        const max = Math.max(datapoint.value, previousDatapoint.value);
        let transitionValues = Array.from(
          { length: TRANSITION_VALUES_COUNT },
          (_, i) => {
            if (i == 0) return datapoint.value;
            if (i == TRANSITION_VALUES_COUNT - 1)
              return previousDatapoint.value;
            const newValue =
              min + (max - min) * (i / (TRANSITION_VALUES_COUNT - 1));
            const parsedValue = Math.round(newValue * 100) / 100;
            return parsedValue;
          }
        ).sort((a, b) => {
          if (datapoint.value > previousDatapoint.value) {
            return a - b;
          } else {
            return b - a;
          }
        });
        datapoint.transitionValues = transitionValues;
      }
      if (nextDataset) {
        const nextDatapoint = nextDataset.data.find(
          (d) => d.normalizedName == datapoint.normalizedName
        );
      }
    });
  });
  return datasets;
}

const scales = {
  x: {
    display: true,
    grid: {
      color: "rgba(255, 255, 255, 0.05)",
    },
    ticks: {
      color: "white",
      font: {
        size: 12,
        style: "normal",
      },
    },
    border: {
      color: "rgba(255, 255, 255, 0.25)",
    },
    min: 0,
    max: 100,
  },
  y: {
    display: true,
    beginAtZero: true,
    position: "left",
    grid: {
      color: "rgba(255, 255, 255, 0.1)",
    },
    border: {
      color: "rgba(255, 255, 255, 0.25)",
    },
    min: 0,
    max: DISPLAY_COUNT - 1,
    ticks: {
      color: function (context) {
        return "white";
      },
      font: function (context) {
        return { size: 14, style: "normal", weight: "bold" };
      },
      callback: function (val, index) {
        const datapoint = datasets[0].data[index];
        return `#${datapoint.rank}`;
      },
    },
  },
};

const optionPlugins = {
  legend: {
    display: false,
  },
  tooltip: {
    enabled: false,
  },
};

const optionAnimations = {
  colors: {
    duration: COLOR_ANIMATION_DURATION,
  },
  y: {
    duration: Y_SCALE_ANIMATION_DURATION,
    easing: "linear",
  },
  x: {
    duration: 0,
    easing: "linear",
  },
};

const optionElements = {
  bar: {
    borderWidth: 2,
  },
};

const plugins = [
  {
    afterDatasetsDraw(chart, args, pluginOptions) {
      if (!afterDatasetsUpdateCalled) {
        return;
      }
      afterDatasetsUpdateCalled = false;
      setOverlayElements(chart, currentDatasetIndex);
    },
    afterDatasetsUpdate(chart, args, pluginOptions) {
      afterDatasetsUpdateCalled = true;
    },
  },
];

const chartOptions = {
  responsive: true,
  aspectRatio: aspectRatio,
  maintainAspectRatio: true,
  indexAxis: "y",
  elements: optionElements,
  animations: optionAnimations,
  responsive: true,
  plugins: optionPlugins,
  scales,
};
